spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_datasource?createDatabaseIfNotExists=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

  eureka:
    client:
      register-with-eureka: true
      fetch-registry:  true

